/*
 * Swagger Offers
 * This is a demo Offers  server developed by atilaek.   [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: atilaek@atilek.atilaek
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Offer;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for OfferApi
 */
@Ignore
public class OfferApiTest {

    private final OfferApi api = new OfferApi();

    /**
     * Add a new offer for merchant
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addOfferTest() throws ApiException {
        Offer body = null;
        api.addOffer(body);

        // TODO: test validations
    }
    /**
     * Deletes a offer
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteOfferTest() throws ApiException {
        Long offerId = null;
        String apiKey = null;
        api.deleteOffer(offerId, apiKey);

        // TODO: test validations
    }
    /**
     * Find offer by ID
     *
     * Returns a single offer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOfferByIdTest() throws ApiException {
        Long offerId = null;
        Offer response = api.getOfferById(offerId);

        // TODO: test validations
    }
    /**
     * Update an existing offer
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateOfferTest() throws ApiException {
        Offer body = null;
        api.updateOffer(body);

        // TODO: test validations
    }
}
